server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 000628
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
